```plantuml
@startuml Withdraw
(*) --> "Send cryptocurrency"
--> ===B1===
-up-> if "Memo" then 
-->[required] "Fill Transaction 
with Payment note"
--> ===B2===
else
-left->[optional] "Fill Basic Transaction"
--> ===B2===

===B1=== -down-> "Send wallet transaction request"
-left-> "Confirm transaction"
-left-> ===B2===

--> (*)

@enduml
```


